USE JSP_MVC2_EX;

CREATE TABLE MAIN_BOARD(
	BOARD_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER 	   VARCHAR(20) NOT NULL,
    SUBJECT    VARCHAR(50) NOT NULL,
    CONTENT    VARCHAR(1000) NOT NULL,
    PASSWD     VARCHAR(20)  NOT NULL,
    READ_CNT   BIGINT DEFAULT 0,
    ENROLL_DT  TIMESTAMP DEFAULT NOW()
);

CREATE TABLE REPLY_BOARD (
	REPLY_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
	WRITER 	   VARCHAR(20) NOT NULL,
    CONTENT    VARCHAR(200) NOT NULL,
    PASSWD     VARCHAR(20) NOT NULL,
	ENROLL_DT  TIMESTAMP DEFAULT NOW(),
	BOARD_ID   BIGINT NOT NULL,
	FOREIGN KEY (BOARD_ID) REFERENCES MAIN_BOARD(BOARD_ID)
	ON DELETE CASCADE
);