USE JSP_MVC2_EX;
	
CREATE TABLE MEMBER(
	MEMBER_ID 		VARCHAR(30)  PRIMARY KEY,
    UUID   			VARCHAR(100) , 
	MEMBER_NM 		VARCHAR(50)  NOT NULL,
	IMG_NM			VARCHAR(500) NOT NULL,
    PASSWD 			VARCHAR(50)  NOT NULL,
	SEX 			VARCHAR(1)   NOT NULL,     
	BIRTH_DT 		VARCHAR(10)  NOT NULL, 
	HP 				VARCHAR(20)  NOT NULL,
	SMSSTS_YN 		VARCHAR(1)   NOT NULL,
	EMAIL 			VARCHAR(50)  NOT NULL,
	EMAILSTS_YN 	VARCHAR(1)   NOT NULL,
	ZIPCODE 		VARCHAR(20)  NOT NULL,
	ROAD_ADDRESS 	VARCHAR(100),
	JIBUN_ADDRESS 	VARCHAR(100),
	NAMUJI_ADDRESS 	VARCHAR(100),
	JOIN_DT 		TIMESTAMP NOT NULL
);
